# Generated by Django 4.1.7 on 2023-03-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drivemate", "0004_product_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="customer",
        ),
    ]
