# Generated by Django 4.1.7 on 2023-04-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivemate", "0009_services_alter_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
