# Generated by Django 4.1.7 on 2023-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivemate", "0010_alter_services_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="description",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
